spring:
  application:
    name: User Registry (Production)
    version: @project.version@

#  datasource:
#    url: jdbc:mysql://prod-db-server:3306/user_registry
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: prod_user
#    password: secure_password

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

  h2:
    console:
      enabled: false # Disable H2 console in production

user:
  allowed-country: France
  min-age: 18

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    com.flaviolcord.user.registry: INFO