spring:
  application:
    name: User Registry (Development)
    version: @project.version@

  datasource:
    url: jdbc:h2:mem:devdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: user
    password: password

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

  h2:
    console:
      enabled: true

user:
  allowed-country: France
  min-age: 18

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    com.flaviolcord.user.registry: TRACE
