name: Deploy Javadoc

on:
  push:
    branches:
      - main
      - gh-pages

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Generate JavaDoc
        run: mvn javadoc:javadoc

      # Create an index.html that redirects to the JavaDoc
      - name: Create redirect index.html
        run: |
          echo '<!DOCTYPE html>
          <html>
            <head>
              <meta http-equiv="refresh" content="0; url=./apidocs/index.html">
            </head>
            <body>
              <p>Please wait while you are redirected to the <a href="./apidocs/index.html">JavaDoc</a>.</p>
            </body>
          </html>' > target/site/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/site    # Changed to include both redirect and JavaDoc
          branch: gh-pages
          clean: true